name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}
      - uses: actions/cache@v2.1.7
        name: Restore gradle cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ env.cache-name }}-
            ${{ runner.OS }}-gradle-
            ${{ runner.OS }}-
      - uses: actions/cache@v2.1.7
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check build

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}
      - uses: actions/cache@v2.1.7
        name: Restore gradle cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-${{ env.cache-name }}-
            ${{ runner.OS }}-gradle-
            ${{ runner.OS }}-
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Publish project
        run: ./gradlew publish -PgithubRepoUsername="${GITHUB_USER}" -PgithubRepoPassword="${GITHUB_TOKEN}"
        env:
          GITHUB_USER: RakSrinaNa
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
